### ISSUE TITLE
Make konstraint doc allow to skip rego code in output

### ISSUE THREAD

**Issue by wayfrro** [plexsystems/konstraint#148]
So there's this cool `konstraint doc` command, but what if target user do not need rego code in docs? It would nice to be still able to generate docs from metadata, but just skip rego code. Do you guys think it's possible?

**Comment by jpreese** [comment]
Definitely possible. A new flag to control whether or not to render the Rego source should do the trick!

**Comment by jalseth** [comment]
Implemented in #154. @wayfrro Please take a look at the example documentation in that PR and confirm it meets your expectations about behavior and output.

**Comment by wayfrro** [comment]
@jalseth That looks good to me. Thanks!
