### ISSUE TITLE
Possible to have constraint and constraint templates created in different directory?

### ISSUE THREAD

**Issue by Jaja0624** [plexsystems/konstraint#162]

**Comment by jalseth** [comment]
Hi @Jaja0624 . This isn't currently possible, but you can use the `--output` flag to write the `Constraint`s and `ConstraintTemplate`s to a specific directory, and then you can have a script move the `template_*.yaml` and `constraint_*.yaml` files to other locations of your choosing. Will that work for your use case?

**Comment by Jaja0624** [comment]
Yes that works. Thanks :)

**Comment by poblahblahblah** [comment]
We've just created a Makefile so we don't have to memorize the command:

```
.PHONY: docs
docs: # Create the docs correctly
    konstraint doc --no-rego --output README.md
```

execution:
```
make docs
```
