### ISSUE TITLE
Version command broke in 0.14.0

### ISSUE THREAD

**Issue by artis3n** [plexsystems/konstraint#173]
Removed from machine and ran `go install` with go 1.16.4 and the `version` command seems to be broken:

![image](https://user-images.githubusercontent.com/6969296/121072494-48339680-c79f-11eb-862b-625f4bbb7f36.png)

**Comment by artis3n** [comment]
Confused with what happens with `go install` vs. the building in the CI workflow and the Dockerfile that explicitly add the template variable, but I am assuming that https://github.com/plexsystems/konstraint/blob/main/internal/commands/default.go#L23 does not get populated without a default during `github.com/plexsystems/konstraint@latest`.

**Comment by jpreese** [comment]
Correct. Using `go install` won't provide a version because the version is set during CI.

**Comment by artis3n** [comment]
Ah so this is intentional? Hard to know when to update if you miss the release notifications from GitHub.

**Comment by jpreese** [comment]
Unless I'm mistaken, it's not possible to set a version when using `go install`. This is the tradeoff between using a pre-built binary or doing it from Go.

**Comment by artis3n** [comment]
That is my understanding too. So your recommended approach is to use the Docker container? If so my suggestion would be to highlight that more directly in the README, above the `go install`.

**Comment by artis3n** [comment]
It is just the version command, not a big deal. Just want to better understand y'all's desire for the project

**Comment by jpreese** [comment]
There really isn't a recommended approach, just whatever is convenient for the end user. I think it's pretty accepted that using a `go install` flow doesn't provide versioning/commit/date details of the build, but is very convenient to use.

**Comment by artis3n** [comment]
Makes sense - my lack of familiarity with publishing go projects, it seems.
