### ISSUE TITLE
Does konstraint support input like Conftest's --data flag?

### ISSUE THREAD

**Issue by artis3n** [plexsystems/konstraint#185]
I have an `import data.thing` in my policy which is read in via `conftest verify --data file.yml --policy ...`.

The `file.yml` looks like:

```yml
thing:
  - 'test1'
  - 'test2'
```

such that `import data.thing` - `thing` matches the array in the yaml file being imported as data.

When I run `konstraint docs` with this policy, I receive the following error:

```
Error: get documentation: get all severities: parse directory: getRecursiveImportPaths: import not found: data.thing
```

How do I tell `konstraint` about the data file for it to resolve the import correctly?

**Comment by jalseth** [comment]
@artis3n Gatekeeper only supports `data.lib.XYZ` imports, so that is also what Konstraint supports. This has caused issues in the past with attempting to have conftest be able to test with input parameters supplied via the `--data` flag (https://github.com/plexsystems/konstraint/issues/108 and https://github.com/plexsystems/konstraint/issues/86). However, it's up to the Gatekeeper team about what is allowed. Relevant discussion is here: https://github.com/open-policy-agent/gatekeeper/issues/1046

**Comment by artis3n** [comment]
Ah ha, thanks for that context. There's the additional difference that the `lib/` directory under the examples in this repo only contains rego files. I don't see any data imports to mimic the yaml that can be passed into `conftest [verify/test] --data`. I am guessing konstraint only supports rego data imports then?

**Comment by jalseth** [comment]
Yes, that is correct. It would be possible to add a `--data` flag that would generate key:value pairs in Rego to include at a pre-determined `data.lib.X` path, but I'd like to have a better understanding of the use case and benefits compared to just including that data in the policy itself or another object that Gatekeeper could sync and use in decisions such as a `ConfigMap`.

**Comment by artis3n** [comment]
I am trying to generate policy documentation from a policy importing data with https://www.conftest.dev/options/#-data

Now I'm not using Gatekeeper...at the moment. We're using Conftest and then using Konstraint solely to generate policy documentation so I'm a bit out there as an edge case . But if this tool is supposed to maintain parity between conftest and gatekeeper I think this request is reasonable.

I have a policy looking at a Dockerfile and saying hey, only these private registries can be used. The registries are currently hard-coded into the rego as a variable but I want to break them out to public the generic policy and let others be able to enter their own registry data without having to change the policy code.

Similarly using Conftest to enforce internal npm packages are published within our npm org scope. Want to publish that policy and similarly want to be able to do that and let other groups pass in `--data` to conftest to set the appropriate npm org while still being able to `conftest pull <policy>` and run it with their data without having to modify the rego source.

And in that world I want to leverage konstraint for nice policy documentation! Although I am not against going and replicating konstraint's policy documentation features in a separate tool that is tied to conftest, not gatekeeper, to handle more flexibility. I know this isn't the focus of your tool.

**Comment by jalseth** [comment]
Ah, OK I understand the intended use case now. Would the documentation include the input from the --data flag somehow? Or do you just need Konstraint to not error in this case?

**Comment by artis3n** [comment]
Yeah I don't see a reason the documentation needs to validate the rego, just mirror it in the markdown. If you want a `--data` flag to do validation that works, but honestly just not checking the content and mirroring the rego source into the documentation would be fine.

**Comment by artis3n** [comment]
I assume the validation is more of a side effect of this? Don't have all the moving pieces in my head yet
https://github.com/plexsystems/konstraint/blob/main/internal/commands/document.go#L112

**Comment by jalseth** [comment]
Well, I think we do want to parse the Rego to make sure it's valid, but we don't need to scan the imports for documentation generation so it sounds like removing that would fit your use case without straying from the purpose of Konstraint. I'll get something together to address this in the next few days.

**Comment by jalseth** [comment]
@artis3n Can you build from https://github.com/jalseth/konstraint/tree/fix-185 and let me know if it resolves your issue?

**Comment by artis3n** [comment]
That successfully generated my documentation in my test that was previously failing, thanks for the quick fix!
![image](https://user-images.githubusercontent.com/6969296/124359457-19b8a800-dbf3-11eb-9200-0a31022b29b2.png)

**Comment by jalseth** [comment]
Great! This has been included in the latest patch release.

**Comment by artis3n** [comment]
Thank you!
