### ISSUE TITLE
Question: Is there any support for passing parameters & namespace selectors into the constraint from the src.rego file?

### ISSUE THREAD

**Issue by zanabizr** [plexsystems/konstraint#21]
I don't see any examples in this repo which clearly show how parameters or namespace selectors could be passed from the `src.rego` file into the `constraint.yaml`. 

Is this something that's possible? Or should I be going about this in a different way?

A basic example I have of the functionality I'd like to use would be to use a list of required labels to enforce on resources created in a cluster. An example constraint file similar to what I described would be - https://github.com/open-policy-agent/gatekeeper/blob/master/example/constraints/all_pod_must_have_gatekeeper_namespaceselector.yaml

**Comment by jpreese** [comment]
As of right now, it's not possible to configure a Namespace selector to generated in the configuration. I'm not opposed to the idea, but I'm not quite sure how best to implement it at the moment.

**Comment by zanabizr** [comment]
Okay thanks for the response on the namespace selector.

As for the parameters, is this something that we should only be doing in the src.rego file?

**Comment by jpreese** [comment]
Fully adopting the idea that you _only_ work with the `src.rego`, yes. Otherwise your parameters would get overwritten when you introduced a change to the policy.

What is your use case to select only certain namespaces for the _policy_? It is possible to configure Gatekeeper itself to ignore certain namespaces.

**Comment by zanabizr** [comment]
I didn't have a particular use case in mind for the namespace specific policies, it was more out of curiosity since I've seen examples of policies created in that way.

**Comment by jpreese** [comment]
@zanabizr no problem, glad you found it useful!

While I agree that being able to specify namespaces is useful, it feels like it should be the last thing to do. If it's a policy _specific_ to that namespace, then I would just put the namespace in the policy itself. If its a policy that should be ignored in certain namespaces, I would have Gatekeeper just ignore that namespace. There's a lot at play here.

If you end up having a direct use-case, please do open another issue!
