### ISSUE TITLE
konstraint create fails on pseudo-import "future.keywords.in"

### ISSUE THREAD

**Issue by asm2git** [plexsystems/konstraint#228]
When running "konstraint create my-policy-dir," I get the following error:

Error: get violations: parse directory: getRecursiveImportPaths: import not found: future.keywords.in

Several of my .rego files contain "import future.keywords.in" which is necessary to enable the Rego keyword "in". However, konstraint appears to be treating that as an actual import and is looking for a file. As I understand it, there is no file to be found, just a change of internal state in Opa's parsing of Rego input.

https://www.openpolicyagent.org/docs/latest/policy-language/#membership-and-iteration-in documents that Opa uses the notation "import future.keywords" in this way.  That link also shows a sample Rego file that uses the "in" keyword. I believe konstraint needs to handle this without generating an error.

Thanks.

**Comment by asm2git** [comment]
I can't submit a pull request, at least, not yet, not without jumping through a few hoops at work, but until then, I believe the following could would fix this problem.

Insert the following lines into internal/rego/rego.go after line 479:

+               if strings.HasPrefix(importPath, "future.keywords") {
+                       continue
+               }

**Comment by jpreese** [comment]
Thanks for reporting this, @asm2git. Your change makes sense to be, and should be resolved via https://github.com/plexsystems/konstraint/pull/230
