### ISSUE TITLE
Add MatchExpressions support

### ISSUE THREAD

**Issue by abinatarajan** [plexsystems/konstraint#237]
I would like to exclude a namespace( or based on label) for only one constraint. Currently I do not see a way to do this. I have done this using matchExpressions. But konstraint is not currently supporting this. Is it possible to add support for this. If not what is the best way to exclude a namespace for only one constraint. Thanks in advance

**Comment by jalseth** [comment]
We can implement support for a `@matchExpressions` annotation similar to what we already have for `@matchLabels` [1].

[1] https://github.com/plexsystems/konstraint/blob/main/docs/constraint_creation.md#annotating-rules-for-matchers

**Comment by jalseth** [comment]
Hi @abinatarajan, this was added in the [latest release v0.19](https://github.com/plexsystems/konstraint/releases/tag/v0.19.0).
