### ISSUE TITLE
Allow user-specified imports to be filtered like data.services

### ISSUE THREAD

**Issue by wiceywkus** [plexsystems/konstraint#243]
We are working with Conftest and Gatekeeper.  And for a particular use case, we need to pass parameters to the template to know what to check for.  We are using @parameter to setup the template; we have a "static" constraint for it. 
Working with Conftest, we followed this guidance: [conftest --data](https://www.conftest.dev/options/#-data), which requires an **import** statement in the template like this:
```
import data.services
ports := services.ports
```
When konstraint sees this, it tries to find the library and path, but does not find it, because Conftest materializes it in the input data documents before passing it to Rego, and throws an error.
Attempts to stub out an "empty" `data/services.rego` package to make konstraint happy (which is straightforward), only results with Gatekeeper rejecting the stubbed out package, because the import's path does not make sense.  In the end, that `import` statement to support Conftest is meaningless to Gatekeeper and probably should be dropped from the template.

Suggestions:
Add a `--filter-import` option to allow the user when running konstraint to tell it to drop specific `import` Rego statements.
For example:
$ konstraint create --output gatekeeper --filter-import data.services

I think this is a generalized idea from #228  and #230.

I do not think it is necessary to remove the rules, since the rules will fail anyway.  So, the user has to code for `data.services.port` and `input.parameters.port`.

Or:
Alternatively, konstraint could recognize this Conftest patter with --data and rewrite the rules replacing `data.services` with `input.parameters`.

Or:
Extend the `@parameter` processing to include a string / pattern to replace in the input template with `input.parameters`.  For example, based on: https://github.com/open-policy-agent/conftest/blob/master/examples/data/policy/base.rego 
```
# @ title example integration with Conftest
# @parameter port string  (maybe konstraint needs a "from data.services" to help the substitutions?) 
import data.lib.core
import data.services

deny[msg] {
	kind == "Service"
	type == "LoadBalancer"

	some p
	input.spec.ports[p].port

	input.spec.ports[p].port == services.port

	msg := sprintf("Cannot expose port %v on LoadBalancer. Denied ports: %v", [input.spec.ports[p].port, services.ports])
}
```
konstraint could rewrite as:
```
import data.lib.core
# import data.services statement removed

deny[msg] {
	kind == "Service"
	type == "LoadBalancer"

	some p
	input.spec.ports[p].port

	input.spec.ports[p].port == input.parameters.port

	msg := sprintf("Cannot expose port %v on LoadBalancer. Denied port: %v", [input.spec.ports[p].port,  input.parameters.port])
}
```

**Comment by jalseth** [comment]
Hello, thank you for the report. I think it may be best if we skip trying to import anything not having a `data.lib.` prefix, as that's all Gatekeeper currently supports [1].

[1] #86

**Comment by wiceywkus** [comment]
Yes, I think so.
I have been building the policy with the import in and testing with Conftest.  For each rule, I have a version for each possible input of parameters, so my setup is ok with this approach.
FYI: When I am ready to commit, I comment out the import statement, run `konstraint create` and `konstraint doc`.  Uncomment the import and then commit the policy to our repos.
For fun, I am using an existing ConfigMap as the source of the parameters, so the import is:
import data.data.  :-)

**Comment by jalseth** [comment]
Hi @wiceywkus, this was added in the [latest release v0.19](https://github.com/plexsystems/konstraint/releases/tag/v0.19.0).
