### ISSUE TITLE
Add support for excludedNamespaces in matcher 

### ISSUE THREAD

**Issue by wiceywkus** [plexsystems/konstraint#244]
Following the Gatekeeper specification: https://open-policy-agent.github.io/gatekeeper/website/docs/howto/#the-match-field 
In addition to @parameter, please add an option @excludedNamespaces in the `match` block when creating Constraints.

**Comment by jalseth** [comment]
Hi @wiceywkus, this was added in https://github.com/plexsystems/konstraint/releases/tag/v0.19.0.
