### ISSUE TITLE
`doc` output is not consistently in the same order

### ISSUE THREAD

**Issue by jalseth** [plexsystems/konstraint#27]
The order of the policies in the `doc` command not consistent, causing the documentation to be slightly different each time. This is because we are iterating over a map which does not necessarily happen in the same order. This was introduced in https://github.com/plexsystems/konstraint/pull/20. 

We can either sort the keys first, or switch from passing around a `map[string]string` to a struct with the file name and contents.

**Comment by jpreese** [comment]
@jalseth This should be already be resolved in the main branch via #25
