### ISSUE TITLE
Use OPA Rego rich metadata instead of custom @annotations

### ISSUE THREAD

**Issue by stek29** [plexsystems/konstraint#277]
OPA v0.38.0 has introduced new rich metadata annotations, which are basically yaml documents embedded in comments

Using those instead of custom `@annotations` might be desirable, to simplify parsing logic and to allow more complicated structures (i.e. #273 would've been much easier with those)

see [OPA Docs on Annotations](https://www.openpolicyagent.org/docs/latest/annotations/)

**Comment by jalseth** [comment]
Hi, thanks for raising this. I think we would be open to making this change (always good to delete unnecessary code!), but would want to also maintain support for the current parsing for a while and include a deprecation warning.

**Comment by jpreese** [comment]
Oh, that looks pretty cool! Would agree we'd want to keep the old logic around for a bit while adopters migrate.

**Comment by stek29** [comment]
It would also be great to have a converter tool from current annotations to new style.
