### ISSUE TITLE
Legacy parameters warning is generated even for new style parameters

### ISSUE THREAD

**Issue by stek29** [plexsystems/konstraint#293]
Warning `Parameters are set with legacy annotations, this functionality will be removed in a future release. Please migrate to OPA Metadata annotations` is printed even when using new style parameters.

headerParams are set from rich annotations too:
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L536-L539
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L570

which causes `create` to believe there are legacy defined parameters present:
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L141-L144
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/commands/create.go#L181-L182

**Comment by jalseth** [comment]
Nice catch! Thanks for identifying the issue and opening a PR.
