### ISSUE TITLE
Templates and Constraint files are not in CamelCasing after running konstraint create

### ISSUE THREAD

**Issue by Frankg26** [plexsystems/konstraint#366]
Hello konstraint team,

First of all, thanks for developing such a useful tool! I utilized it in Q4 2021 and it was just what I needed to enforce some OPA policies.

I am reaching out because I have to revisit the work I previously did and add new policies. Konstraint is showcasing some new behaviour, that at first I thought it was an update. However, upon looking at the **Resource Naming** section of your [documentation](https://github.com/plexsystems/konstraint/blob/main/docs/constraint_creation.md), I believe this is not what happened. When I run the `konstraint create` command, the Template and Constraint yaml files are created in lower case as opposed to camel casing. 

Here is a [screenshot](https://imgur.com/a/1q8d8iW) of my directory (simplified for this issue) after running the command `konstraint create opa --output yaml`. I was expecting konstraint to name the two files in the yaml folder **constraint_FrankTestCasing.yaml** and **template_FrankTestCasing.yaml**. But as you can see, the names of the files are not in camel case. When I worked with konstraint in the past, I always got camel casing after running `konstraint create`. 

Furthermore, the **kind** key-value inside both the constraint and template yaml files is **Franktestcasing** as opposed to **FrankTestCasing**. Here is a [screenshot](https://imgur.com/a/S8gCzDA) of the constraint file.

I installed konstraint in my new Mac two days ago, so I am running on the latest version. Is this behaviour something you guys have encountered in the past? Or perhaps is a setting I can change? Any help is appreciated, thanks!

**Comment by jpreese** [comment]
The casing comes from the hyphens. So in your case your directory should be `opa/frank-test-casing/src.rego`

**Comment by Frankg26** [comment]
Hello, 

Thank you for the response. I renamed my directory as you suggested and the issue has been solved! 

Was the usage of hyphens introduced in 2022? Because the directory `opa/FrankTestCasing/src.rego`, would have resulted in camel casing for the templates and constraint files when I used Konstraint back in Q4 2021.

**Comment by jpreese** [comment]
Not that I recall, I thought we always did it by hyphens to match how the Gatekeeper library laid theirs out.

For science, you could try downloading an older version and testing again.

**Comment by jalseth** [comment]
The naming has been in place since 2020-09-08, see the Git blame link below. I believe this issue should be closed, as this is the expected behavior.

https://github.com/plexsystems/konstraint/blame/8e2b39c77d0d98d84187cecba0c7f7b2d122c429/internal/rego/rego.go#L382

**Comment by Frankg26** [comment]
Thank you for the responses!
