### ISSUE TITLE
containerdenyescalation

### ISSUE THREAD

**Issue by rjbrown57** [plexsystems/konstraint#447]
Hello! Thanks for the excellent project!

I noticed today that [containerdenyescalation](https://github.com/plexsystems/konstraint/blob/700f72da554fceadbbc3369f84769b50002a1557/examples/container-deny-escalation/src.rego#L38) doesn't seem to be behaving exactly as intended.  

If a pod has `securityContext: {}` defined then it will be admitted. Since `allowPrivilegeEscalation` is defaulted to true in most cases would it make sense to update this policy?

I fixed this locally adding 
```
container_allows_escalation(c) {
	core.missing_field(c, "securityContext")
}
```

**Comment by jpreese** [comment]
Thanks for reporting this, @rjbrown57 

Your proposal makes sense to me, are you interested in creating a PR for this?

**Comment by rjbrown57** [comment]
Sure thing. I'll try to submit it today
