### ISSUE TITLE
Error: parse policies: imported library not found

### ISSUE THREAD

**Issue by garethahealy** [plexsystems/konstraint#7]
I am trying to create the constraints for:
- https://github.com/redhat-cop/rego-policies

But, hitting an issue:
```
$ konstraint create
Error: parse policies: imported library not found: data.utils.kubernetes
Usage:
  konstraint create <dir> [flags]

Flags:
  -h, --help   help for create

Global Flags:
      --ignore string   A regex pattern which can be used for ignoring directories and files (default "^$")
      --lib string      The name of the folder where the Rego librarie(s) are (default "lib")
```

From the error message, it seems to be complaining about:
- https://github.com/redhat-cop/rego-policies/blob/master/policy/deny-k8s-rolebinding-roleref.rego#L3

which lives here:
- https://github.com/redhat-cop/rego-policies/blob/master/policy/utils/kubernetes.rego

conftest doesn't complain, so I presume its valid rego. Any idea?

**Comment by jpreese** [comment]
You'll most likely need to either change your `utils` folder to `lib` or set the `--lib` flag to utils.

**Comment by garethahealy** [comment]
yep, user error :)

On the auto discovering the libs: Yep, that would be nice/make it easier.

**Comment by jpreese** [comment]
Awesome, glad to hear! Closing.
