### ISSUE TITLE
Request: Add type of rego to docs

### ISSUE THREAD

**Issue by garethahealy** [plexsystems/konstraint#8]
It would be nice if the docs included the type of constraint being violented in the docs, i.e.: if it's a deny/warn/etc

i.e.:

|Type|API Groups|Kinds|Description|
|---|---|---|---|
|DENY|apps, core|DaemonSet, Deployment, StatefulSet, Pod|Container images can not use the latest tag.|
|WARN|apps, core|DaemonSet, Deployment, StatefulSet, Pod|Containers must have resource constraints specified.|

Ideally, this would be worked out from the rego and not from the comment.

**Comment by garethahealy** [comment]
And also maybe a link to rego file?

**Comment by jpreese** [comment]
@garethahealy couple of clarifications.

1. Is the intent to use the documentation outside of the context of Gatekeeper? Gatekeeper requires that all rules are named `violation[]`, so the type would always be `Violation`. I'm not opposed to adding a type as it could be valuable in other scenarios.

2. Would you intend for documentation and rego to live in the same repository? If the documentation was published to a static site, I'm not sure how we could link back to the rego. Thoughts: CLI flag specifying repository URL? A Konstraint config file?

**Comment by garethahealy** [comment]
1. Yes, I am thinking about conftest as well, where I'd have `warn` policies.
2. Yes, docs would live with rego, as-is now. I am thinking of someone going to a GitHub repo, seeing what's in the policies.md and then wanting to see how that policy is written. Currently, they'd need to search GH for the comment.

re: 2 static sites. If you provided a repo URL, you might need to build the full URL to the rego depending on what's provided, i.e.: github vs gitlab URLs are slightly different. Might get messy quickly.
