### ISSUE TITLE
Bug: Comments interpreted in policy documentation generation

### ISSUE THREAD

**Issue by artis3n** [plexsystems/konstraint#88]
I have a 

```
# @title ATitle
#
# A paragraph description
#
# @enforcement deny
```

setup on a rego policy but Konstraint is adding the comments inside my rego to the policy documentation, which I do not want.

For example:

![image](https://user-images.githubusercontent.com/6969296/100660098-8c8d3800-331f-11eb-8aa0-23f9311a47a9.png)

This comment is included in the generated policy documentation:

![image](https://user-images.githubusercontent.com/6969296/100660450-09b8ad00-3320-11eb-8853-0f7d48d91b00.png)

That seems like a bug

Reproduce:
- Write an arbitrary policy
- Include the Konstraint policy doc stuff above the `package` declaration
- Add a `#` comment inside the rego code
- Observe the generated policy markdown includes the comment in the documentation description.

**Comment by jalseth** [comment]
Konstraint [treats](https://github.com/plexsystems/konstraint/blob/279945ba1f170f4bd8d6c9a2f586a781736ace7c/internal/rego/rego.go#L181-L183) the `@kinds` tag as the end of the header block when parsing the policy description. This was selected when `@kinds` was the only tag Konstraint supported, so this may need a refresh. 

Since all of the `@` tags are optional and can exist in any order, it may be best to add an `@end` tag or something similar so Konstraint can easily know when a comment is no longer a part of the header block. What are your thoughts @artis3n @jpreese ?

**Comment by artis3n** [comment]
Ah, and I don't use the `@kind` tag because I'm writing policies beyond just kubernetes - using Konstraint for policy documentation of the rest of what Conftest can test as well as k8s.

I understand Konstraint is primarily a tool to templatize policies between Conftest and Gatekeeper, but to leverage its policy self-documentation utilities - I would prefer Konstraint to use the contiguous block of comments above a `package` declaration / at the top of a file and ignore any other comments in the file. Then, the content can exist in that contiguous block in any order, and anything _within_ that contiguous comment block that does not begin with `@` should be treated as part of the policy description.

read lines in file, while line begins with `#`, treat as part of policy header, break when line no longer begins with `#`. But it doesn't [look like you maintain the file structure](https://github.com/plexsystems/konstraint/blob/279945ba1f170f4bd8d6c9a2f586a781736ace7c/internal/rego/rego.go#L177) when parsing the Rego, you have _all_ comments in the file and have to work with that. If that is the case, then adding a `@end` works. That suggests there should be a `@begin` or `@start` highlighting the start of where Konstraint should look for policy declaration - if the `r.comments` is ordered such that the comment lines appear in the same order that they are written in the file, earlier lines first.

I have used Go, many years ago, and have only interacted with rego for writing policies. So hopefully my comments make sense for the tools we have in the language.

**Comment by jalseth** [comment]
That sounds good, and it shouldn't be too hard to implement. I'll probably have time to get to this next week.

**Comment by jalseth** [comment]
@artis3n this was implemented in #104 and it seems to work in my testing. Can you try with your policies and let me know if you run into any issues?

**Comment by artis3n** [comment]
Will check on Monday

**Comment by artis3n** [comment]
Git diff shows this fixing the issue! Comments are removed from the generated documentation

![image](https://user-images.githubusercontent.com/6969296/102114999-e81ff100-3e08-11eb-9c2f-e4e5ce7604a5.png)

**Comment by artis3n** [comment]
Is there any particular cadence to Konstraint's release cycle? It would be nice to take advantage of this fix but I don't see that https://github.com/plexsystems/konstraint/pull/104 has been released.

**Comment by jalseth** [comment]
@artis3n We don't have any formal release schedule at the moment, but I think it would be fair to target monthly at a minimum going forward, with a release every 2 weeks being a stretch goal. @jpreese do you have any thoughts?
