### ISSUE TITLE
examples: Breakdown kubernetes library into smaller pieces

### ISSUE THREAD

**Issue by jpreese** [plexsystems/konstraint#9]
The `kubernetes.rego` file in the examples folder contains all rules for every potential use case. Importing the entire library into every `ConstraintTemplate` is a bit heavy-handed.

One approach could be:

- Break up the library such that the rules relate to specific workloads / concerns. To make Gatekeeper compliant with Conftest, the only _requirements_ are the `is_gatekeeper` and `object` rules. The remainders are nice to haves. This could be `kubernetes.core`.

- All of the memory/size conversions are only needed in some container policies. This could be `kubernetes.conversions`.

This enables policy writers to opt-in to specific rulesets and keep the imported rules small.

**Comment by jalseth** [comment]
I've started on this and have made good progress. I'll have PR up in a day or two.

**Comment by jpreese** [comment]
Closed via #29
